---
abstract: 'Export Org document to HTML'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Org-Export-HTML
requires:
  Org::Parser: 0.07
  String::Escape: 0
  Sub::Spec::CmdLine: 0
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Org-Export-HTML/
  repository: http://github.com/sharyanto/perl-Org-Export-HTML
version: 0.01
